export const CATEGORY_SELECTED_UPDATE = 'CATEGORY/SELECTED/UPDATE';
export const CATEGORY_SELECTED_ATTEMPT = 'CATEGORY/SELECTED/UPDATE/ATTEMPT';
export const CATEGORY_UPDATE_FAILED = 'CATEGORY/UPDATE/FAILED';
